spring:
  application:
    name:
    - grafana-prometheus-loki
management:
  endpoints:
    web:
      exposure:
        include:
          health, info, prometheus
  endpoint:
    prometheus:
      enabled:
        true